// <auto-generated />
using System;
using ACI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ACI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260206140000_AddTemplateOrganizationFields")]
    partial class AddTemplateOrganizationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a partial migration - adds Template organization fields
            // Full model snapshot is in AppDbContextModelSnapshot.cs
#pragma warning restore 612, 618
        }
    }
}
