// Export helpers for the activity history (CSV for Google Sheets/Excel + a
// print-to-PDF view that needs no extra dependency).

import type { Activity } from '@/app/api/types';
import type { CsvColumn } from './exportCsv';

function fmtDateTime(iso?: string): string {
  if (!iso) return '';
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? '' : d.toLocaleString(undefined, { dateStyle: 'medium', timeStyle: 'short' });
}

export function activityTypeLabel(type?: string): string {
  if (!type) return '';
  return type.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export function activityRelatedTo(a: Activity): string {
  if (a.contactName) return `${a.contactName} (contact)`;
  if (a.dealName) return `${a.dealName} (deal)`;
  if (a.leadName) return `${a.leadName} (lead)`;
  return '';
}

/** Columns for the CSV export (opens directly in Google Sheets / Excel). */
export const activityCsvColumns: CsvColumn<Activity>[] = [
  { header: 'Date', value: (a) => fmtDateTime(a.createdAt) },
  { header: 'Type', value: (a) => activityTypeLabel(a.type) },
  { header: 'Subject', value: (a) => a.subject },
  { header: 'Details', value: (a) => a.body },
  { header: 'Related to', value: (a) => activityRelatedTo(a) },
  { header: 'Logged by', value: (a) => a.createdByName || a.createdByEmail },
];

function esc(s: string | undefined): string {
  return (s ?? '').replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string));
}

/**
 * Open a print-optimized report of the activities and trigger the browser's
 * print dialog (where the user can "Save as PDF"). Returns false if the popup
 * was blocked so the caller can surface a hint.
 */
export function printActivitiesPdf(rows: Activity[], meta: { subtitle?: string } = {}): boolean {
  const win = window.open('', '_blank', 'width=920,height=720');
  if (!win) return false;

  const exportedAt = new Date().toLocaleString(undefined, { dateStyle: 'long', timeStyle: 'short' });
  const body = rows
    .map(
      (a) => `
      <tr>
        <td class="date">${esc(fmtDateTime(a.createdAt))}</td>
        <td><span class="type">${esc(activityTypeLabel(a.type))}</span></td>
        <td>${esc(a.subject) || '<span class="muted">—</span>'}${a.body ? `<div class="body">${esc(a.body)}</div>` : ''}</td>
        <td>${esc(activityRelatedTo(a)) || '<span class="muted">—</span>'}</td>
        <td>${esc(a.createdByName || a.createdByEmail) || '<span class="muted">—</span>'}</td>
      </tr>`,
    )
    .join('');

  win.document.write(`<!doctype html>
<html><head><meta charset="utf-8"><title>Activity history</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif; color: #0f172a; margin: 32px; }
  .head { display:flex; align-items:flex-end; justify-content:space-between; border-bottom:2px solid #ea580c; padding-bottom:12px; margin-bottom:20px; }
  .brand { font-size:20px; font-weight:800; letter-spacing:-0.01em; }
  .brand span { color:#ea580c; }
  h1 { font-size:15px; margin:2px 0 0; font-weight:600; color:#334155; }
  .meta { text-align:right; font-size:12px; color:#64748b; line-height:1.5; }
  table { width:100%; border-collapse:collapse; font-size:12px; }
  thead th { text-align:left; background:#f8fafc; color:#64748b; font-size:10px; text-transform:uppercase; letter-spacing:0.05em; padding:8px 10px; border-bottom:1px solid #e2e8f0; }
  tbody td { padding:9px 10px; border-bottom:1px solid #f1f5f9; vertical-align:top; }
  tbody tr { page-break-inside: avoid; }
  td.date { white-space:nowrap; color:#475569; }
  .type { display:inline-block; padding:1px 8px; border-radius:999px; background:#fff7ed; color:#c2410c; font-weight:600; font-size:11px; }
  .body { color:#64748b; margin-top:2px; font-size:11px; }
  .muted { color:#cbd5e1; }
  .footer { margin-top:18px; font-size:11px; color:#94a3b8; }
  @media print { body { margin:12mm; } thead { display: table-header-group; } }
</style></head>
<body>
  <div class="head">
    <div>
      <div class="brand">Cadence<span>.</span></div>
      <h1>Activity history</h1>
    </div>
    <div class="meta">
      ${meta.subtitle ? esc(meta.subtitle) + '<br>' : ''}${rows.length} ${rows.length === 1 ? 'entry' : 'entries'}<br>Exported ${esc(exportedAt)}
    </div>
  </div>
  <table>
    <thead><tr><th style="width:130px">Date</th><th style="width:90px">Type</th><th>Activity</th><th style="width:150px">Related to</th><th style="width:120px">Logged by</th></tr></thead>
    <tbody>${body || '<tr><td colspan="5" class="muted" style="padding:24px;text-align:center">No activities to export.</td></tr>'}</tbody>
  </table>
  <div class="footer">Generated by Cadence</div>
  <script>window.onload = function(){ setTimeout(function(){ window.print(); }, 150); };</script>
</body></html>`);
  win.document.close();
  win.focus();
  return true;
}
